// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAw_ZkShlTgqh_0tiFsWPAnASUrbBdJMY',
    appId: '1:150075016163:web:06409eeabdbe30f549d6d6',
    messagingSenderId: '150075016163',
    projectId: 'punjai-3a73b',
    authDomain: 'punjai-3a73b.firebaseapp.com',
    storageBucket: 'punjai-3a73b.firebasestorage.app',
    measurementId: 'G-Z8W672W9GF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKhCPokt4sOOZVoDEg0QzXCeL1YsOSLVI',
    appId: '1:150075016163:android:618451102b73f6c849d6d6',
    messagingSenderId: '150075016163',
    projectId: 'punjai-3a73b',
    storageBucket: 'punjai-3a73b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOqCiy9NRxsYs7Gm4RqLlUfvVoO7N2N6s',
    appId: '1:150075016163:ios:630c661927199ff649d6d6',
    messagingSenderId: '150075016163',
    projectId: 'punjai-3a73b',
    storageBucket: 'punjai-3a73b.firebasestorage.app',
    iosBundleId: 'com.example.punjaiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOqCiy9NRxsYs7Gm4RqLlUfvVoO7N2N6s',
    appId: '1:150075016163:ios:630c661927199ff649d6d6',
    messagingSenderId: '150075016163',
    projectId: 'punjai-3a73b',
    storageBucket: 'punjai-3a73b.firebasestorage.app',
    iosBundleId: 'com.example.punjaiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAw_ZkShlTgqh_0tiFsWPAnASUrbBdJMY',
    appId: '1:150075016163:web:3911d2bcf4dd524949d6d6',
    messagingSenderId: '150075016163',
    projectId: 'punjai-3a73b',
    authDomain: 'punjai-3a73b.firebaseapp.com',
    storageBucket: 'punjai-3a73b.firebasestorage.app',
    measurementId: 'G-8BBZ2ZXXQ1',
  );
}
